### ISSUE TITLE
Include sample files to better understand inputs

### ISSUE THREAD

**Issue by MikeRee** [DiceTechJobs/ConceptualSearch#1]
Trying to better understand the inputs for the scripts and it would be nice to see some samples. If they already exists I must have missed them.

Thanks,
Mike

**Comment by simonhughes22** [comment]
Sure i'll try and get that. I have some example outputs in the SolrConfigExamples as they are solr synonym files, but no example inputs. The keywords and phrases are just a file containing a word or phrase per line. The documents are raw text, which can contain html.

**Comment by simonhughes22** [comment]
Mike, I will also try and create a single script with less options, so it's easier for people to run. Right now it's 4 separate steps as some are optional and I wanted to make it flexible. And that was how I had developed it so simplest to port quickly and open source. But the current form is not in the most consumable format. I will be working to address that. I have some bandwith to spend work hours on this also, as management feel this is a good tool to give to the community.

**Comment by MikeRee** [comment]
Awesome, I read over all your scripts and they made sense, I was just questioning the format and requirements of the inputs.

IE: The html parser fucntions. I did a wiki html dump really quick and the scripts didn't product anything. So I started to generated other sample files to try and further test the scripts. If I had sample inputs I could more easily just checkout and run the scripts in order and better understand what is really happening from reading the source and looking at the inputs -> outputs.

Thanks for the help, was a good talk and interest in playing with this a little more.

**Comment by simonhughes22** [comment]
Glad you like it. I am using beautifulsoup to parse html. It's not perfect though, it may barf on complex pages. I certainly found some js coming back in some docs, so you may want to pre-parse the wiki pages somehow with a better tool. Incidentally, the gensim author (wrote the Word2Vec library I'm using) has a good tutorial on using gensim on wikipedia, including some basic wiki markup parsing. Although again it's not perfect: https://radimrehurek.com/gensim/wiki.html

**Comment by simonhughes22** [comment]
The usual wiki dump is in XML too, the code I am using is assuming a html doc structure or plain text. So that may be why it's not working. You can try turning off the html parsing option to see if you get something that way, although it will be noisy

**Comment by MikeRee** [comment]
No, I have a local wikipedia and crawled the html pages and saved as files
in a folder. So they where html.

Mike

**Comment by simonhughes22** [comment]
@MikeRee can you send me a few of the sample html files? Either upload to dropbox or similar, or send as a pull request in a separate subfolder of this project? I've asked permission for us to share a small subset of our data, but that could take a while to get approved.

**Comment by MikeRee** [comment]
I tried to attach a file but it requires write permissions to the repo. What's your email? I'll email you an example.

**Comment by simonhughes22** [comment]
@MikeRee simon.hughes@dice.com

**Comment by simonhughes22** [comment]
@MikeRee - sorry I haven't forgot about this. Had some major fires to put out. Will get on this shortly hopefully

**Comment by simonhughes22** [comment]
Anyone who has questions, please post a GItHub issue to this repository, and @mention me and then I will respond. That way other people can see the response.

**Comment by Sandy4321** [comment]
Hi guys, did you managed to upload some input files? Is it possible to find synonyms for phrase like for software developer it will be Computer programmer ??

**Comment by simonhughes22** [comment]
@Sandy4321 I provided some sample files here: https://github.com/DiceTechJobs/ConceptualSearch/tree/master/sample%20input%20files . I can't provide our list of learned synonyms as that is proprietary data. word2vec or whatever you use should find that software developer is similar to computer programmer, although whether they are in the top k similar terms depends on the value for k. They should get pushed into the same cluster if the cluster size is large enough (i.e. the number of clusters is small enough).
