### ISSUE TITLE
Is ConceptualSearch applicable for ElasticSearch?

### ISSUE THREAD

**Issue by tokestermw** [DiceTechJobs/ConceptualSearch#2]
Hi, thanks for this great example of combining word2vec with Lucene / Solr. How transferable is your code to Elastic Search? I ask only because AWS has an ElasticSearch Service which would be convenient to use.

**Comment by simonhughes22** [comment]
Sorry for the late reply, I just saw this. I am not that familiar with ES,  but I am assuming it uses the same file format as it's also Lucene based so it should work. The plugins I have developed won't work out of the box, but they are not needed for the clustering version output, which is the easiest to get going with anyways. Let me know if you have any other questions

**Comment by simonhughes22** [comment]
Please note - If anyone has any questions, please include @simonhughes22 in the issue otherwise I won't get an email and may miss updates if I haven't checked in a while.

**Comment by simonhughes22** [comment]
If you just use the synonym file output by the clustering approach, it would work fine in ES
