### ISSUE TITLE
Config Issue in dicetechjobs/conceptual search - @simonhughes22

### ISSUE THREAD

**Issue by smitra01** [DiceTechJobs/ConceptualSearch#4]
trying out the generate_topn_synonyms_file.py and getting the following error 
------------------------------
  File "D:\Sanghamitra\WorkPad\GIS\Solution-N-Explore\Automation\Incubation
\search\ConceptualSearch-master\generate_cluster_synonyms_file.py", line 65
<module>
    config = GenerateClusterSynonymsConfig(sys.argv[1])
  File "D:\Sanghamitra\WorkPad\GIS\Solution-N-Explore\Automation\Incubation
\search\ConceptualSearch-master\Config\generate_cluster_synonyms_config.py"
e 8, in __init__
    self.keywords_files = self.__getstring__("DEFAULT", "keyword_files").sp
,")
  File "D:\Sanghamitra\WorkPad\GIS\Solution-N-Explore\Automation\Incubation
\search\ConceptualSearch-master\Config\config_base.py", line 15, in __getst
_
    value = self.__cfg__.get(section, key)
  File "C:\Python27\lib\ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'keyword_files' in section: 'DEFAULT'

-------------------------------
modified the file path with the path of my mchine in generate_topn_synonyms.cfg

Attaching the file for reference
[generate_topn_synonyms.txt](https://github.com/DiceTechJobs/ConceptualSearch/files/1571586/generate_topn_synonyms.txt)

I am new to python -- so not able to figure out, if I am missing any thing; how to resolve the error.

**Comment by simonhughes22** [comment]
You are missing the 'keyword_files' setting in DEFAULT section of the *.cfg file.

**Comment by smitra01** [comment]
Hello Simon , 

Many thanks for the response! 

I have added the 'keyword_files'  setting in the .cfg file,  just the way you have done so (attached generate_topn_synonyms.txt for ready reference)

#keyword_files:                      /Users/simon.hughes/Documents/Dice Data/LuceneTalk/Phrases.txt,/Users/simon.hughes/Documents/Dice Data/LuceneTalk/top_5k_keywords.txt
keyword_files:                      C:\InputDocs\Phrases.txt,C:\InputDocs\top_5k_keywords.txt

Still getting the error 

In fact the 'keyword_files' setting is working fine for the other example train_word2vec_model.py, but giving error in both generate_topn_synonyms.py and nerate_cluster_synonyms_file.py. 

Can you please help me to resolve this error so that I can proceed with the execution

**Comment by simonhughes22** [comment]
It has to be in the [DEFAULT] section of the config, please see this for reference: https://github.com/DiceTechJobs/ConceptualSearch/blob/master/Settings/generate_topn_synonyms.cfg . Please make sure you are spelling the setting correctly, the files exist (i.e. the paths are correct) and they are comma delimited if there is more than one file listed. If you are still having issues, please post the config file here for me to look at. Thanks

**Comment by simonhughes22** [comment]
I just saw the previous attachment. The error may be miss leading, you have two copies of the payload_synonyms_file which could cause issues. I stripped out everything else from the file, try this:

[DEFAULT]
keyword_files:                      C:\InputDocs\Phrases.txt,C:\InputDocs\top_5k_keywords.txt
top_n:                              10
word2vec_model_file:   		    C:\InputDocs\keyword_model.w2v
payload_synonyms_file:              C:\InputDocs\top10_keyword_synonyms.txt
synonyms_file:                      C:\InputDocs\keyword_synonyms.txt

**Comment by simonhughes22** [comment]
Also, I haven't tested this code on Windows. It could be that the drive letter followed by the ':' is confusing python's parser. The first entry in the file is the 'keyword_files' entry, so likely the error is again misleading. I would look into how to escape special chars like colons in python config files (I am using a standard python format here, nothing home grown), or specify the paths without the drive letter.

**Comment by smitra01** [comment]
Hi,

After modifying the path as suggested by you , the earlier problem got resolved. I could execute extract_keywords.py (2) and train_word2vec_model.py(3).

But got following error while executing generate_topn_synonyms_file.py

D:\Sanghamitra\WorkPad\GIS\Solution-N-Explore\Automation\Incubation-2017\search\
ConceptualSearch-master>python generate_topn_synonyms_file.py ./Settings/generat
e_topn_synonyms.cfg
C:\Python27\lib\site-packages\gensim-3.2.0-py2.7-win32.egg\gensim\utils.py:860:
UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
Word2Vec model loaded
44 keywords loaded in total
Traceback (most recent call last):
  File "generate_topn_synonyms_file.py", line 64, in <module>
    missing, no_sim, processed_syns = write_most_similar_synonyms(config.top_n,
keywords, model, config.payload_synonyms_file, config.synonyms_file)
  File "generate_topn_synonyms_file.py", line 17, in write_most_similar_synonyms

    if not word in model.vocab:
AttributeError: 'Word2Vec' object has no attribute 'vocab'

Is there problem with the input data.

Sharing the input files, config files and execution log for 2,3 and 4, for ready reference (in the input.zip).
Can you help me to resolve the error.

Thanks & Regards,
Sanghamitra

**Comment by smitra01** [comment]
On further analysis, it seems to me that there may be issue in the input data – due to which the model is nt created properly

It is possible to share a sample input data set for train_word2vec_model and generate_topn_synonyms

For train_word2vec_model, dice_stop_words.txt and top_5k_keywords.txt is already there in the example set, need to have Phrases.txt and some sample doc for the processed_documents_folder.

As per my current understanding, this should be sufficient to execute generate_topn_synonyms.py as well – please validate.

Once I can run with this sample data set successfully, in the similar line, I can create data for my own scenario.

Looking forward for your response for faster execution!

Regards,
Sanghamitra
From: Mitra, Sanghamitra
Sent: Wednesday, January 3, 2018 4:03 PM
To: DiceTechJobs/ConceptualSearch <reply@reply.github.com>; DiceTechJobs/ConceptualSearch <ConceptualSearch@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [DiceTechJobs/ConceptualSearch] Config Issue in dicetechjobs/conceptual search - @simonhughes22 (#4)

Hi,

After modifying the path as suggested by you , the earlier problem got resolved. I could execute extract_keywords.py (2) and train_word2vec_model.py(3).

But got following error while executing generate_topn_synonyms_file.py

D:\Sanghamitra\WorkPad\GIS\Solution-N-Explore\Automation\Incubation-2017\search\
ConceptualSearch-master>python generate_topn_synonyms_file.py ./Settings/generat
e_topn_synonyms.cfg
C:\Python27\lib\site-packages\gensim-3.2.0-py2.7-win32.egg\gensim\utils.py:860:
UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
Word2Vec model loaded
44 keywords loaded in total
Traceback (most recent call last):
  File "generate_topn_synonyms_file.py", line 64, in <module>
    missing, no_sim, processed_syns = write_most_similar_synonyms(config.top_n,
keywords, model, config.payload_synonyms_file, config.synonyms_file)
  File "generate_topn_synonyms_file.py", line 17, in write_most_similar_synonyms

    if not word in model.vocab:
AttributeError: 'Word2Vec' object has no attribute 'vocab'

Is there problem with the input data.

Sharing the input files, config files and execution log for 2,3 and 4, for ready reference (in the input.zip).
Can you help me to resolve the error.

Thanks & Regards,
Sanghamitra

**Comment by smitra01** [comment]
Hello,


Could solve the problem, was a version problem it seems – used model.wv.vocab

 Instead of model.vocab (as the gensim 1.0.0+) in generate_topn_synonyms_file.

Thanks and Regards

From: Mitra, Sanghamitra
Sent: Thursday, January 4, 2018 9:02 AM
To: 'DiceTechJobs/ConceptualSearch' <reply@reply.github.com>; 'DiceTechJobs/ConceptualSearch' <ConceptualSearch@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [DiceTechJobs/ConceptualSearch] Config Issue in dicetechjobs/conceptual search - @simonhughes22 (#4)


On further analysis, it seems to me that there may be issue in the input data – due to which the model is nt created properly

It is possible to share a sample input data set for train_word2vec_model and generate_topn_synonyms

For train_word2vec_model, dice_stop_words.txt and top_5k_keywords.txt is already there in the example set, need to have Phrases.txt and some sample doc for the processed_documents_folder.

As per my current understanding, this should be sufficient to execute generate_topn_synonyms.py as well – please validate.

Once I can run with this sample data set successfully, in the similar line, I can create data for my own scenario.

Looking forward for your response for faster execution!

Regards,
Sanghamitra
From: Mitra, Sanghamitra
Sent: Wednesday, January 3, 2018 4:03 PM
To: DiceTechJobs/ConceptualSearch <reply@reply.github.com>; DiceTechJobs/ConceptualSearch <ConceptualSearch@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [DiceTechJobs/ConceptualSearch] Config Issue in dicetechjobs/conceptual search - @simonhughes22 (#4)

Hi,

After modifying the path as suggested by you , the earlier problem got resolved. I could execute extract_keywords.py (2) and train_word2vec_model.py(3).

But got following error while executing generate_topn_synonyms_file.py

D:\Sanghamitra\WorkPad\GIS\Solution-N-Explore\Automation\Incubation-2017\search\
ConceptualSearch-master>python generate_topn_synonyms_file.py ./Settings/generat
e_topn_synonyms.cfg
C:\Python27\lib\site-packages\gensim-3.2.0-py2.7-win32.egg\gensim\utils.py:860:
UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
Word2Vec model loaded
44 keywords loaded in total
Traceback (most recent call last):
  File "generate_topn_synonyms_file.py", line 64, in <module>
    missing, no_sim, processed_syns = write_most_similar_synonyms(config.top_n,
keywords, model, config.payload_synonyms_file, config.synonyms_file)
  File "generate_topn_synonyms_file.py", line 17, in write_most_similar_synonyms

    if not word in model.vocab:
AttributeError: 'Word2Vec' object has no attribute 'vocab'

Is there problem with the input data.

Sharing the input files, config files and execution log for 2,3 and 4, for ready reference (in the input.zip).
Can you help me to resolve the error.

Thanks & Regards,
Sanghamitra

**Comment by simonhughes22** [comment]
Yes that code was written about 2 years ago. It looks like they've updated the interface since then.
