### ISSUE TITLE
Invalid syntax when mapping in tokenized_docs

### ISSUE THREAD

**Issue by kemalcankara** [DiceTechJobs/ConceptualSearch#6]
Hi Simon,

Ty very much for the code. Im trying to understand your work with my own data. But i get invalid syntax error. As im a newbie in python, i couldnt figure out how to correct it. The error is below:

 File "<ipython-input-48-6d05abc4d3b9>", line 1
    working_docs = [map(lambda func(sid, sent): (sid, [sent]), d) for d in tokenized_docs]
                                   ^
SyntaxError: invalid syntax

Can you help me with that?

**Comment by simonhughes22** [comment]
Sorry for the late reply. I believe that is to do with the version of python you are using. The code was written in python 2.7, in 3.0 they added some changes that made how you call lambdas stricter such that lines like that one won't work.
